import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useCount} from '../context/Control'

export default function Home() {


  const { count } = useCount();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      




      
    </div>
  )
}
